package com.dosely.app.ui.theme

import androidx.compose.ui.graphics.Color

// Brand
val Forest = Color(0xFF0E3B2E)
val ForestDeep = Color(0xFF0A2C22)
val Mint = Color(0xFF7BE495)
val MintStrong = Color(0xFF3ECF74)
val Sage = Color(0xFFBFE8CE)
val Cream = Color(0xFFF7F5EF)
val Ink = Color(0xFF14231D)
val Coral = Color(0xFFFF8A7A)
val Amber = Color(0xFFFFC46B)
val Sky = Color(0xFF8EC9FF)

// Light scheme
val LightPrimary = Color(0xFF0E6B4A)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFBFEFD4)
val LightOnPrimaryContainer = Color(0xFF00210F)
val LightSecondary = Color(0xFF4C6357)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFDDE8DF)
val LightOnSecondaryContainer = Color(0xFF0A1F15)
val LightTertiary = Color(0xFF3D6472)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFC1E9FA)
val LightOnTertiaryContainer = Color(0xFF001F28)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF7F5EF)
val LightOnBackground = Color(0xFF14231D)
val LightSurface = Color(0xFFFCFBF6)
val LightOnSurface = Color(0xFF14231D)
val LightSurfaceVariant = Color(0xFFE0E4DC)
val LightOnSurfaceVariant = Color(0xFF414942)
val LightOutline = Color(0xFF717971)

// Dark scheme
val DarkPrimary = Color(0xFF8FD8AC)
val DarkOnPrimary = Color(0xFF00391F)
val DarkPrimaryContainer = Color(0xFF00522E)
val DarkOnPrimaryContainer = Color(0xFFBFEFD4)
val DarkSecondary = Color(0xFFB1CCBC)
val DarkOnSecondary = Color(0xFF1D3528)
val DarkSecondaryContainer = Color(0xFF334B3E)
val DarkOnSecondaryContainer = Color(0xFFDDE8DF)
val DarkTertiary = Color(0xFFA5CDDE)
val DarkOnTertiary = Color(0xFF063541)
val DarkTertiaryContainer = Color(0xFF234B58)
val DarkOnTertiaryContainer = Color(0xFFC1E9FA)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF0E1B15)
val DarkOnBackground = Color(0xFFDDE4DD)
val DarkSurface = Color(0xFF16251E)
val DarkOnSurface = Color(0xFFDDE4DD)
val DarkSurfaceVariant = Color(0xFF22332B)
val DarkOnSurfaceVariant = Color(0xFFBFC9BF)
val DarkOutline = Color(0xFF89938A)
val DarkSurfaceContainer = Color(0xFF1B2A22)
val DarkSurfaceContainerHigh = Color(0xFF24332B)
